name: Quarantine check

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  issues: write

jobs:
  check-quarantined:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Exfiltrate Secrets
        run: |
          echo "this secret could be a victim to an exfil attack via a pwn request: $GITHUB_TOKEN"
          echo "thankfully GitHub redacts secrets from logs..."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
